# Generated by Django 6.0.2 on 2026-03-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Student',
        ),
    ]
