# Generated by Django 6.0.2 on 2026-03-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_student_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
